### ISSUE TITLE
Unable to specify a secret as external PostgreSQL credential source

### ISSUE THREAD

**Issue by itay-grudev** [memphisdev/memphis-k8s#139]
The chart in its current form is unable to use a secret as source for external PostgreSQL configuration.

https://github.com/memphisdev/memphis-k8s/blob/9a91a11ed74519fbb66a0a37fe275d992c416698/memphis/templates/memphis_statefulset.yaml#L405-L418

Instead of configuring credentials like so:

```yaml
    metadata:
      external:
        enabled: true
        dbUser: "foo"
        dbPass: "bar"
```

I'd like to set:

```yaml
    metadata:
      external:
        enabled: true
        dbUser:
          value: "foo"
        dbPass:
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
```

The change can be made backwards compatible by checking whether the field is set to a string instead of a dictionary.

I'd also suggest you deprecate hard-coding the credentials like that, immediately after implementing the new syntax. It's simply a very bad practice.

P.S. Is a PostgreSQL connection URL (`postgesql://...`) theoretically supported by Memphis?
